spring.application.name=f1-stats-api

# Server port (React runs on 5173, so we use 8080)
server.port=8080

# PostgreSQL config (we'll set up DB next)
spring.datasource.url=jdbc:postgresql://localhost:5432/f1stats
spring.datasource.username=postgres
spring.datasource.password=postgrade

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Allow React to call this API
spring.web.cors.allowed-origins=http://localhost:5173
