#spring.application.name=f1-stats-api
#server.port=${PORT:8080}
#
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
##FRONTEND_URL = https://f1-stat-explorer-frontend-git-main-nayangorias-projects.vercel.app
spring.application.name=f1-stats-api
server.port=${PORT:8080}

spring.datasource.url=${postgresql://f1stats_user:X54GlPJtDnuOTAV4As3HDIPn7QqQnwPj@dpg-d883mrmk1jcs73eaocc0-a.singapore-postgres.render.com/f1stats:jdbc:postgresql://localhost:5432/f1stats}
spring.datasource.username=${f1stats_user:postgrade}
spring.datasource.password=${X54GlPJtDnuOTAV4As3HDIPn7QqQnwPjSPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false